Cutelee: Cutelee::RenderContext Class Reference
Cutelee::RenderContext Class Reference
Provides storage facility for state while rendering a template.
#include <rendercontext.h>
Public Member Functions
~RenderContext ()
bool contains (Node *const scopeNode) const
QVariant & data (const Node *const scopeNode)
Detailed Description
This class can not be instatiated by users of it. An instance of RenderContext is available through Context::renderContext() for use with implementations of re-entrant template tags.
Definition at line 46 of file rendercontext.h.
Constructor & Destructor Documentation
~RenderContext()
RenderContext::~RenderContext ()
Destructor
Definition at line 43 of file rendercontext.cpp.
Member Function Documentation
contains()
bool RenderContext::contains (Node *const scopeNode) const
Returns whether the RenderContext contains data for scopeNode.
Definition at line 51 of file rendercontext.cpp.
Referenced by BlockNode::getSuper().
data()
QVariant & RenderContext::data (const Node *const scopeNode)
Returns the data for the node scopeNode.
Definition at line 58 of file rendercontext.cpp.
Referenced by BlockNode::getSuper(), CycleNode::render(), BlockNode::render(), ExtendsNode::render(), and ConstantIncludeNode::render().