Cutelee: LineBreaksBrFilter Class Reference
LineBreaksBrFilter Class Reference
Public Member Functions
QVariant doFilter (const QVariant &input, const QVariant &argument={}, bool autoescape={}) const override
bool isSafe () const override
Public Member Functions inherited from Cutelee::Filter
virtual ~Filter ()
SafeString conditionalEscape (const SafeString &input) const
SafeString escape (const QString &input) const
SafeString escape (const SafeString &input) const
Detailed Description
Definition at line 244 of file stringfilters.h.
Member Function Documentation
doFilter()
QVariant LineBreaksBrFilter::doFilter (const QVariant & input, const QVariant & argument = {}, bool autoescape = {}) const override virtual
Reimplement to filter input given argument.
autoescape determines whether the autoescape feature is currently on or off. Most filters will not use this.
See also
Autoescaping and safe-ness
Implements Cutelee::Filter.
Definition at line 450 of file stringfilters.cpp.
References Cutelee::Filter::conditionalEscape(), Cutelee::getSafeString(), Cutelee::isSafeString(), and Cutelee::markSafe().
isSafe()
bool LineBreaksBrFilter::isSafe () const inline override virtual
Reimplement to return whether this filter is safe.
Reimplemented from Cutelee::Filter.
Definition at line 250 of file stringfilters.h.