Cutelee: L10nFileSizeNode Class Reference
L10nFileSizeNode Class Reference
Public Member Functions
L10nFileSizeNode (const FilterExpression &size, const FilterExpression &unitSystem, const FilterExpression &precision, const FilterExpression &multiplier, QObject *parent=nullptr)
void render (OutputStream *stream, Context *c) const override
Public Member Functions inherited from Cutelee::Node
Node (QObject *parent={})
~Node () override
Additional Inherited Members
Protected Member Functions inherited from Cutelee::Node
TemplateImpl * containerTemplate () const
void streamValueInContext (OutputStream *stream, const QVariant &input, Cutelee::Context *c) const
Detailed Description
Definition at line 50 of file l10n_filesize.h.
Member Function Documentation
render()
void L10nFileSizeNode::render (OutputStream * stream, Context * c) const override virtual
Reimplement this to render the template in the Context c.
This will also involve calling render on and child nodes.
Implements Cutelee::Node.
Definition at line 102 of file l10n_filesize.cpp.
References Cutelee::calcFileSize(), Cutelee::SafeString::get(), Cutelee::getSafeString(), Cutelee::FilterExpression::isValid(), Cutelee::Context::localizer(), Cutelee::FilterExpression::resolve(), and Cutelee::Node::streamValueInContext().