Cutelee: BlockNode Class Reference
BlockNode Class Reference
Public Member Functions
BlockNode (const QString &blockName, QObject *parent={})
void addParent (NodeList)
SafeString getSuper () const
QString name () const
NodeList nodeList () const
void render (OutputStream *stream, Context *c) const override
void setNodeList (const NodeList &list) const
void setNodeParent (BlockNode *)
BlockNode * takeNodeParent ()
Public Member Functions inherited from Cutelee::Node
Node (QObject *parent={})
~Node () override
Properties
Cutelee::SafeString super
Additional Inherited Members
Protected Member Functions inherited from Cutelee::Node
TemplateImpl * containerTemplate () const
void streamValueInContext (OutputStream *stream, const QVariant &input, Cutelee::Context *c) const
Detailed Description
Definition at line 42 of file block.h.
Member Function Documentation
getSuper()
SafeString BlockNode::getSuper () const
Returns the block overridden by this one rendered in context.
Definition at line 145 of file block.cpp.
References Cutelee::OutputStream::clone(), Cutelee::RenderContext::contains(), Cutelee::RenderContext::data(), Cutelee::markSafe(), render(), and Cutelee::Context::renderContext().
render()
void BlockNode::render (OutputStream * stream, Context * c) const override virtual
Reimplement this to render the template in the Context c.
This will also involve calling render on and child nodes.
Implements Cutelee::Node.
Definition at line 103 of file block.cpp.
References Cutelee::RenderContext::data(), Cutelee::Context::insert(), Cutelee::Context::pop(), Cutelee::Context::push(), Cutelee::NodeList::render(), and Cutelee::Context::renderContext().
Referenced by getSuper().