Cutelee: FilterNode Class Reference
FilterNode Class Reference
Public Member Functions
FilterNode (const FilterExpression &fe, QObject *parent={})
void render (OutputStream *stream, Context *c) const override
void setNodeList (const NodeList &filterList)
Public Member Functions inherited from Cutelee::Node
Node (QObject *parent={})
~Node () override
Additional Inherited Members
Protected Member Functions inherited from Cutelee::Node
TemplateImpl * containerTemplate () const
void streamValueInContext (OutputStream *stream, const QVariant &input, Cutelee::Context *c) const
Detailed Description
Definition at line 36 of file filtertag.h.
Member Function Documentation
render()
void FilterNode::render (OutputStream * stream, Context * c) const override virtual
Reimplement this to render the template in the Context c.
This will also involve calling render on and child nodes.
Implements Cutelee::Node.
Definition at line 70 of file filtertag.cpp.
References Cutelee::OutputStream::clone(), Cutelee::Context::insert(), Cutelee::Context::pop(), Cutelee::Context::push(), Cutelee::NodeList::render(), and Cutelee::FilterExpression::resolve().