Cutelee: Cutelee::FileSystemTemplateLoader Class Reference
Cutelee::FileSystemTemplateLoader Class Reference
The FileSystemTemplateLoader loads Templates from the file system.
#include <templateloader.h>
Public Member Functions
FileSystemTemplateLoader (const std::shared_ptr< AbstractLocalizer > localizer={})
~FileSystemTemplateLoader () override
bool canLoadTemplate (const QString &name) const override
std::pair< QString, QString > getMediaUri (const QString &fileName) const override
Template loadByName (const QString &name, Engine const *engine) const override
void setTemplateDirs (const QStringList &dirs)
void setTheme (const QString &themeName)
QStringList templateDirs () const
QString themeName () const
Public Member Functions inherited from Cutelee::AbstractTemplateLoader
virtual ~AbstractTemplateLoader ()
Detailed Description
This template loader works by traversing a list of directories to find templates. Directories are checked in order, and the first match hit is parsed and returned.
loader->setTemplateDirs({
    "/home/user/app/templates",
    "/usr/local/share/app/templates"
});
engine->setTemplateLoader(loader);
// This will try /home/user/app/templates/mytemplate.html
// followed by /usr/local/share/app/templates/mytemplate.html
engine->loadByName("mytemplate.html");
Additionally, a themeName may be set on the template loader, which will be appended to search paths before the template name.
loader->setTemplateDirs({
  "/home/user/app/templates" <<
  "/usr/local/share/app/templates"
});
loader->setTheme("simple_theme");
engine->setTemplateLoader(loader);
// This will try /home/user/app/templates/simple_theme/mytemplate.html
// followed by /usr/local/share/app/templates/simple_theme/mytemplate.html
engine->loadByName("mytemplate.html");
Media URIs may be retrieved for media relative to the directories searched queried for templates.
loader->setTemplateDirs({
  "/home/user/app/templates",
  "/usr/local/share/app/templates"
});
loader->setTheme("simple_theme");
engine->setTemplateLoader(loader);
// This will try /home/user/app/templates/simple_theme/logo.png
// followed by /usr/local/share/app/templates/simple_theme/logo.png
// and return the first one that exists.
engine->mediaUri("logo.png");
The template files loaded by a %**FileSystemTemplateLoader** must be UTF-8 encoded.
See also
Deploying Templates
Definition at line 135 of file templateloader.h.
Constructor & Destructor Documentation
FileSystemTemplateLoader()
FileSystemTemplateLoader::FileSystemTemplateLoader (const std::shared_ptr< AbstractLocalizer > localizer = {})
Constructor
Definition at line 56 of file templateloader.cpp.
~FileSystemTemplateLoader()
FileSystemTemplateLoader::~FileSystemTemplateLoader () override
Destructor
Definition at line 63 of file templateloader.cpp.
References templateDirs(), and themeName().
Member Function Documentation
canLoadTemplate()
bool FileSystemTemplateLoader::canLoadTemplate (const QString & name) const override virtual
Return true if a Template identified by name exists and can be loaded.
Implements Cutelee::AbstractTemplateLoader.
Definition at line 108 of file templateloader.cpp.
getMediaUri()
std::pair< QString, QString > FileSystemTemplateLoader::getMediaUri (const QString & fileName) const override virtual
Return a complete URI for media identified by fileName.
Implements Cutelee::AbstractTemplateLoader.
Definition at line 168 of file templateloader.cpp.
loadByName()
Template FileSystemTemplateLoader::loadByName (const QString & name, Engine const * engine) const override virtual
Load a Template called name. Return an invalid Template if no content by that name exists.
Implements Cutelee::AbstractTemplateLoader.
Definition at line 130 of file templateloader.cpp.
References Cutelee::Engine::newTemplate().
setTemplateDirs()
void FileSystemTemplateLoader::setTemplateDirs (const QStringList & dirs)
Sets the directories to look for template files to dirs.
Definition at line 90 of file templateloader.cpp.
References templateDirs().
setTheme()
void FileSystemTemplateLoader::setTheme (const QString & themeName)
Sets the theme of this loader to themeName
Definition at line 74 of file templateloader.cpp.
References templateDirs(), and themeName().
templateDirs()
QStringList FileSystemTemplateLoader::templateDirs () const
The directories this TemplateLoader looks in for template files.
Definition at line 102 of file templateloader.cpp.
Referenced by ~FileSystemTemplateLoader(), setTemplateDirs(), and setTheme().
themeName()
QString FileSystemTemplateLoader::themeName () const
The themeName of this TemplateLoader
Definition at line 84 of file templateloader.cpp.
Referenced by ~FileSystemTemplateLoader(), and setTheme().