Cutelee: ConstantIncludeNode Class Reference
ConstantIncludeNode Class Reference
Public Member Functions
ConstantIncludeNode (const QString &filename, QObject *parent={})
void render (OutputStream *stream, Context *c) const override
Public Member Functions inherited from Cutelee::Node
Node (QObject *parent={})
~Node () override
Additional Inherited Members
Protected Member Functions inherited from Cutelee::Node
TemplateImpl * containerTemplate () const
void streamValueInContext (OutputStream *stream, const QVariant &input, Cutelee::Context *c) const
Detailed Description
Definition at line 53 of file include.h.
Member Function Documentation
render()
void ConstantIncludeNode::render (OutputStream * stream, Context * c) const override virtual
Reimplement this to render the template in the Context c.
This will also involve calling render on and child nodes.
Implements Cutelee::Node.
Definition at line 87 of file include.cpp.
References Cutelee::Node::containerTemplate(), Cutelee::RenderContext::data(), and Cutelee::Context::renderContext().