Cutelee: WithLocaleNodeFactory Class Reference
WithLocaleNodeFactory Class Reference
Public Member Functions
Node * getNode (const QString &tagContent, Parser *p) const override
Public Member Functions inherited from Cutelee::AbstractNodeFactory
AbstractNodeFactory (QObject *parent={})
~AbstractNodeFactory () override
Additional Inherited Members
Protected Member Functions inherited from Cutelee::AbstractNodeFactory
QList< FilterExpression > getFilterExpressionList (const QStringList &list, Parser *p) const
Q_INVOKABLE QStringList smartSplit (const QString &str) const
Detailed Description
Definition at line 28 of file with_locale.h.
Member Function Documentation
getNode()
Node * WithLocaleNodeFactory::getNode (const QString & tagContent, Parser * p) const override virtual
This method should be reimplemented to return a Node which can be rendered.
The tagContent is the content of the tag including the tag name and arguments. For example, if the template content is {% my_tag arg1 arg2 %}, the tagContent will be "my_tag arg1 arg2".
The Parser p is available and can be advanced if appropriate. For example, if the tag has an end tag, the parser can be advanced to the end tag.
See also
tags
Implements Cutelee::AbstractNodeFactory.
Definition at line 32 of file with_locale.cpp.
References Cutelee::Parser::parse(), Cutelee::Parser::removeNextToken(), and Cutelee::AbstractNodeFactory::smartSplit().