Cutelee: ForNode Class Reference
ForNode Class Reference
Public Types
enum Reversed { IsNotReversed , IsReversed }
Public Member Functions
ForNode (const QStringList &loopVars, const FilterExpression &fe, int reversed, QObject *parent={})
void render (OutputStream *stream, Context *c) const override
void setEmptyList (const NodeList &emptyList)
void setLoopList (const NodeList &loopNodeList)
Public Member Functions inherited from Cutelee::Node
Node (QObject *parent={})
~Node () override
Additional Inherited Members
Protected Member Functions inherited from Cutelee::Node
TemplateImpl * containerTemplate () const
void streamValueInContext (OutputStream *stream, const QVariant &input, Cutelee::Context *c) const
Detailed Description
Definition at line 37 of file for.h.
Member Function Documentation
render()
void ForNode::render (OutputStream * stream, Context * c) const override virtual
Reimplement this to render the template in the Context c.
This will also involve calling render on and child nodes.
Implements Cutelee::Node.
Definition at line 136 of file for.cpp.
References Cutelee::Context::insert(), Cutelee::Context::lookup(), Cutelee::Context::pop(), Cutelee::Context::push(), Cutelee::NodeList::render(), and Cutelee::FilterExpression::resolve().