Cutelee: IfChangedNode Class Reference
IfChangedNode Class Reference
Public Member Functions
IfChangedNode (const QList< FilterExpression > &feList, QObject *parent={})
void render (OutputStream *stream, Context *c) const override
void setFalseList (const NodeList &falseList)
void setTrueList (const NodeList &trueList)
Public Member Functions inherited from Cutelee::Node
Node (QObject *parent={})
~Node () override
Additional Inherited Members
Protected Member Functions inherited from Cutelee::Node
TemplateImpl * containerTemplate () const
void streamValueInContext (OutputStream *stream, const QVariant &input, Cutelee::Context *c) const
Detailed Description
Definition at line 37 of file ifchanged.h.
Member Function Documentation
render()
void IfChangedNode::render (OutputStream * stream, Context * c) const override virtual
Reimplement this to render the template in the Context c.
This will also involve calling render on and child nodes.
Implements Cutelee::Node.
Definition at line 72 of file ifchanged.cpp.
References Cutelee::OutputStream::clone(), Cutelee::Context::insert(), Cutelee::Context::lookup(), Cutelee::Context::pop(), Cutelee::Context::push(), and Cutelee::NodeList::render().