Cutelee: Cutelee::AbstractLocalizer Class Reference
Cutelee::AbstractLocalizer Class Reference abstract
Interface for implementing an internationalization system.
#include <abstractlocalizer.h>
Public Member Functions
AbstractLocalizer ()
virtual ~AbstractLocalizer ()
virtual QString currentLocale () const =0
virtual void loadCatalog (const QString &path, const QString &catalog)=0
virtual QString localize (const QVariant &variant) const
virtual QString localizeContextString (const QString &string, const QString &context, const QVariantList &arguments={}) const =0
virtual QString localizeDate (const QDate &date, QLocale::FormatType formatType=QLocale::ShortFormat) const =0
virtual QString localizeDateTime (const QDateTime &dateTime, QLocale::FormatType formatType=QLocale::ShortFormat) const =0
virtual QString localizeMonetaryValue (qreal value, const QString &currencyCode={}) const =0
virtual QString localizeNumber (int number) const =0
virtual QString localizeNumber (qreal number) const =0
virtual QString localizePluralContextString (const QString &string, const QString &pluralForm, const QString &context, const QVariantList &arguments={}) const =0
virtual QString localizePluralString (const QString &string, const QString &pluralForm, const QVariantList &arguments={}) const =0
virtual QString localizeString (const QString &string, const QVariantList &arguments={}) const =0
virtual QString localizeTime (const QTime &time, QLocale::FormatType formatType=QLocale::ShortFormat) const =0
virtual void popLocale ()=0
virtual void pushLocale (const QString &localeName)=0
virtual void unloadCatalog (const QString &catalog)=0
Detailed Description
This class defines an interface for accessing an internationalization, such as QLocale/QTranslator or gettext/KLocale.
Author
Stephen Kelly steve.nosp@m.ire@.nosp@m.gmail.nosp@m..com
Definition at line 42 of file abstractlocalizer.h.
Constructor & Destructor Documentation
AbstractLocalizer()
AbstractLocalizer::AbstractLocalizer ()
Constructor
Definition at line 29 of file abstractlocalizer.cpp.
~AbstractLocalizer()
AbstractLocalizer::~AbstractLocalizer () virtual
Destructor
Definition at line 31 of file abstractlocalizer.cpp.
Member Function Documentation
currentLocale()
virtual QString Cutelee::AbstractLocalizer::currentLocale () const pure virtual
Returns the current locale as a string.
Implemented in Cutelee::QtLocalizer.
loadCatalog()
virtual void Cutelee::AbstractLocalizer::loadCatalog (const QString & path, const QString & catalog) pure virtual
Loads the catalog from path.
Implemented in Cutelee::QtLocalizer.
localize()
QString AbstractLocalizer::localize (const QVariant & variant) const virtual
Processes the data in variant into a localized string.
The base implementation can localize numbers, dates and times, and strings.
Definition at line 33 of file abstractlocalizer.cpp.
References Cutelee::getSafeString(), Cutelee::isSafeString(), localizeDate(), localizeDateTime(), localizeNumber(), localizeString(), and localizeTime().
localizeContextString()
virtual QString Cutelee::AbstractLocalizer::localizeContextString (const QString & string, const QString & context, const QVariantList & arguments = {}) const pure virtual
Localizes string, disambiguated by context with the specified arguments for substitution
Implemented in Cutelee::QtLocalizer.
localizeDate()
virtual QString Cutelee::AbstractLocalizer::localizeDate (const QDate & date, QLocale::FormatType formatType = QLocale::ShortFormat) const pure virtual
Localizes date with the specified formatType
Implemented in Cutelee::QtLocalizer.
Referenced by localize().
localizeDateTime()
virtual QString Cutelee::AbstractLocalizer::localizeDateTime (const QDateTime & dateTime, QLocale::FormatType formatType = QLocale::ShortFormat) const pure virtual
Localizes dateTime with the specified formatType
Implemented in Cutelee::QtLocalizer.
Referenced by localize().
localizeMonetaryValue()
virtual QString Cutelee::AbstractLocalizer::localizeMonetaryValue (qreal value, const QString & currencyCode = {}) const pure virtual
Localizes value as a monetary value in the currency specified by currencyCode.
Implemented in Cutelee::QtLocalizer.
localizeNumber() [1/2]
virtual QString Cutelee::AbstractLocalizer::localizeNumber (int number) const pure virtual
Localizes number
Implemented in Cutelee::QtLocalizer.
Referenced by localize().
localizeNumber() [2/2]
virtual QString Cutelee::AbstractLocalizer::localizeNumber (qreal number) const pure virtual
Localizes number
Implemented in Cutelee::QtLocalizer.
localizePluralContextString()
virtual QString Cutelee::AbstractLocalizer::localizePluralContextString (const QString & string, const QString & pluralForm, const QString & context, const QVariantList & arguments = {}) const pure virtual
Localizes string or its pluralForm, disambiguated by context with the specified arguments for substitution
Implemented in Cutelee::QtLocalizer.
localizePluralString()
virtual QString Cutelee::AbstractLocalizer::localizePluralString (const QString & string, const QString & pluralForm, const QVariantList & arguments = {}) const pure virtual
Localizes string or its pluralForm with the specified arguments for substitution
Implemented in Cutelee::QtLocalizer.
localizeString()
virtual QString Cutelee::AbstractLocalizer::localizeString (const QString & string, const QVariantList & arguments = {}) const pure virtual
Localizes string with the specified arguments for substitution
Implemented in Cutelee::QtLocalizer.
Referenced by localize().
localizeTime()
virtual QString Cutelee::AbstractLocalizer::localizeTime (const QTime & time, QLocale::FormatType formatType = QLocale::ShortFormat) const pure virtual
Localizes time with the specified formatType
Implemented in Cutelee::QtLocalizer.
Referenced by localize().
popLocale()
virtual void Cutelee::AbstractLocalizer::popLocale () pure virtual
Makes this localizer use the previous locale for output.
Implemented in Cutelee::QtLocalizer.
pushLocale()
virtual void Cutelee::AbstractLocalizer::pushLocale (const QString & localeName) pure virtual
Makes this localizer use the locale specified by localeName for output.
Implemented in Cutelee::QtLocalizer.
unloadCatalog()
virtual void Cutelee::AbstractLocalizer::unloadCatalog (const QString & catalog) pure virtual
Unloads the catalog
Implemented in Cutelee::QtLocalizer.