Cutelee: RegroupNode Class Reference
RegroupNode Class Reference
Public Member Functions
RegroupNode (const FilterExpression &target, const FilterExpression &expression, const QString &varName, QObject *parent={})
void render (OutputStream *stream, Context *c) const override
Public Member Functions inherited from Cutelee::Node
Node (QObject *parent={})
~Node () override
Additional Inherited Members
Protected Member Functions inherited from Cutelee::Node
TemplateImpl * containerTemplate () const
void streamValueInContext (OutputStream *stream, const QVariant &input, Cutelee::Context *c) const
Detailed Description
Definition at line 37 of file regroup.h.
Member Function Documentation
render()
void RegroupNode::render (OutputStream * stream, Context * c) const override virtual
Reimplement this to render the template in the Context c.
This will also involve calling render on and child nodes.
Implements Cutelee::Node.
Definition at line 64 of file regroup.cpp.
References Cutelee::getSafeString(), Cutelee::Context::insert(), Cutelee::Context::pop(), Cutelee::Context::push(), Cutelee::FilterExpression::resolve(), and Cutelee::FilterExpression::toList().